"""initial schema

Revision ID: e06e20237418
Revises:
Create Date: 2026-09-04 15:31:24.320790
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e06e20237418'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.Enum('thought', 'feeling', 'experience', 'contradiction', 'question', 'quote', 'context', name='materialkind', native_enum=False), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('privacy', sa.Enum('private', 'anonymized', 'shareable', name='privacy', native_enum=False), nullable=False),
    sa.Column('preserve_verbatim', sa.Boolean(), nullable=False),
    sa.Column('recorded_at', sa.String(length=40), nullable=False),
    sa.Column('recorded_at_epoch_ms', sa.BigInteger(), nullable=False),
    sa.Column('effective_at', sa.String(length=40), nullable=False),
    sa.Column('effective_at_epoch_ms', sa.BigInteger(), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materials_effective_at_epoch_ms'), 'materials', ['effective_at_epoch_ms'], unique=False)
    op.create_index(op.f('ix_materials_public_id'), 'materials', ['public_id'], unique=True)
    op.create_index(op.f('ix_materials_recorded_at_epoch_ms'), 'materials', ['recorded_at_epoch_ms'], unique=False)
    op.create_table('personal_propositions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=32), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('origin_source_proposition_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('privacy', sa.Enum('private', 'anonymized', 'shareable', name='privacy', native_enum=False), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personal_propositions_origin_source_proposition_id'), 'personal_propositions', ['origin_source_proposition_id'], unique=False)
    op.create_index(op.f('ix_personal_propositions_public_id'), 'personal_propositions', ['public_id'], unique=True)
    op.create_table('response_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=40), nullable=False),
    sa.Column('target_id', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=30), nullable=False),
    sa.Column('recorded_at', sa.String(length=40), nullable=False),
    sa.Column('recorded_at_epoch_ms', sa.BigInteger(), nullable=False),
    sa.Column('recorded_date', sa.String(length=10), nullable=False),
    sa.Column('daily_ordinal', sa.Integer(), nullable=False),
    sa.Column('effective_at', sa.String(length=40), nullable=False),
    sa.Column('effective_at_epoch_ms', sa.BigInteger(), nullable=False),
    sa.Column('time_precision', sa.Enum('minute', 'day', 'month', 'year', 'unknown', name='timeprecision', native_enum=False), nullable=False),
    sa.Column('resonance', sa.Enum('high', 'medium', 'low', 'none', 'unspecified', name='resonance', native_enum=False), nullable=False),
    sa.Column('agreement', sa.Enum('agree', 'mostly_agree', 'partly_agree', 'uncertain', 'disagree', 'unspecified', name='agreement', native_enum=False), nullable=False),
    sa.Column('adoption', sa.Enum('adopt', 'adapt', 'cite', 'not_use', 'undecided', name='adoption', native_enum=False), nullable=False),
    sa.Column('confidence', sa.Enum('low', 'medium', 'high', name='confidence', native_enum=False), nullable=False),
    sa.Column('original_words', sa.Text(), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('assistant_summary', sa.Text(), nullable=True),
    sa.Column('supersedes', sa.String(length=40), nullable=True),
    sa.Column('creates_personal_proposition_id', sa.String(length=32), nullable=True),
    sa.CheckConstraint('daily_ordinal > 0', name='positive_daily_ordinal'),
    sa.ForeignKeyConstraint(['supersedes'], ['response_events.public_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recorded_date', 'daily_ordinal')
    )
    op.create_index(op.f('ix_response_events_effective_at_epoch_ms'), 'response_events', ['effective_at_epoch_ms'], unique=False)
    op.create_index(op.f('ix_response_events_public_id'), 'response_events', ['public_id'], unique=True)
    op.create_index(op.f('ix_response_events_recorded_at_epoch_ms'), 'response_events', ['recorded_at_epoch_ms'], unique=False)
    op.create_index(op.f('ix_response_events_recorded_date'), 'response_events', ['recorded_date'], unique=False)
    op.create_index(op.f('ix_response_events_target_id'), 'response_events', ['target_id'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.Enum('web_article', 'book', 'video', 'podcast', 'speech', 'conversation', 'other', name='sourcekind', native_enum=False), nullable=False),
    sa.Column('platform', sa.String(length=200), nullable=True),
    sa.Column('original_url', sa.Text(), nullable=False),
    sa.Column('canonical_url', sa.Text(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('creator', sa.String(length=300), nullable=True),
    sa.Column('publisher', sa.String(length=300), nullable=True),
    sa.Column('published_at', sa.String(length=80), nullable=True),
    sa.Column('language', sa.String(length=40), nullable=True),
    sa.Column('topics', sa.JSON(), nullable=False),
    sa.Column('stance', sa.Enum('pending', 'endorsed', 'partially_endorsed', 'reference', 'questioned', 'opposed', name='sourcestance', native_enum=False), nullable=False),
    sa.Column('stance_as_of', sa.String(length=40), nullable=True),
    sa.Column('content_status', sa.Enum('registered', 'metadata_only', 'summarized', 'mapped', 'cited', 'unavailable', name='contentstatus', native_enum=False), nullable=False),
    sa.Column('rights', sa.Enum('third_party_copyright', 'licensed', 'public_domain', 'user_owned', 'unknown', name='rights', native_enum=False), nullable=False),
    sa.Column('raw_archive_path', sa.Text(), nullable=True),
    sa.Column('raw_archive_sha256', sa.String(length=64), nullable=True),
    sa.Column('raw_archive_bytes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_public_id'), 'sources', ['public_id'], unique=True)
    op.create_table('thought_maps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('version', sa.String(length=30), nullable=False),
    sa.Column('privacy', sa.Enum('private', 'anonymized', 'shareable', name='privacy', native_enum=False), nullable=False),
    sa.Column('source_material_ids', sa.JSON(), nullable=False),
    sa.Column('nodes', sa.JSON(), nullable=False),
    sa.Column('edges', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_thought_maps_public_id'), 'thought_maps', ['public_id'], unique=True)
    op.create_table('source_propositions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('attribution', sa.Enum('author_explicit', 'collaborator_summary', name='propositionattribution', native_enum=False), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'ordinal')
    )
    op.create_index(op.f('ix_source_propositions_public_id'), 'source_propositions', ['public_id'], unique=True)
    op.create_index(op.f('ix_source_propositions_source_id'), 'source_propositions', ['source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_source_propositions_source_id'), table_name='source_propositions')
    op.drop_index(op.f('ix_source_propositions_public_id'), table_name='source_propositions')
    op.drop_table('source_propositions')
    op.drop_index(op.f('ix_thought_maps_public_id'), table_name='thought_maps')
    op.drop_table('thought_maps')
    op.drop_index(op.f('ix_sources_public_id'), table_name='sources')
    op.drop_table('sources')
    op.drop_index(op.f('ix_response_events_target_id'), table_name='response_events')
    op.drop_index(op.f('ix_response_events_recorded_date'), table_name='response_events')
    op.drop_index(op.f('ix_response_events_recorded_at_epoch_ms'), table_name='response_events')
    op.drop_index(op.f('ix_response_events_public_id'), table_name='response_events')
    op.drop_index(op.f('ix_response_events_effective_at_epoch_ms'), table_name='response_events')
    op.drop_table('response_events')
    op.drop_index(op.f('ix_personal_propositions_public_id'), table_name='personal_propositions')
    op.drop_index(op.f('ix_personal_propositions_origin_source_proposition_id'), table_name='personal_propositions')
    op.drop_table('personal_propositions')
    op.drop_index(op.f('ix_materials_recorded_at_epoch_ms'), table_name='materials')
    op.drop_index(op.f('ix_materials_public_id'), table_name='materials')
    op.drop_index(op.f('ix_materials_effective_at_epoch_ms'), table_name='materials')
    op.drop_table('materials')
    # ### end Alembic commands ###
